lighthouse:
  sensor:
    checkRate: 30  # time in seconds between sensor state checks
    timeout: 60    # time in seconds to pass without reports before the sensor is considered unpowered
    password: changeme
  fcm:
    creds-file: firebase-credentials.json
  telegram:
    token: 1234567890:secrettoken
    chat-id: -1002158828917

logging:
  level:
    ua.org.meters.lighthouse: DEBUG
